### ISSUE TITLE
Reported crash of Teads Service when app on background

### ISSUE THREAD

**Issue by rslama** [teads/TeadsSDK-android#107]
Fatal Exception: java.lang.RuntimeException: Unable to start receiver tv.teads.teadsevent.StartServiceReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxx.xxx/tv.teads.teadsevent.service.EventService }: app is in background uid UidRecord{ec48523 u0a228 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3264)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:251)
       at android.app.ActivityThread.main(ActivityThread.java:6563)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

In project we're using TeadsSKD v. 2.5.7

**Comment by HugoGresse** [comment]
Hi Robert,
Thanks for reporting it, we'll release a new SDK version today or tomorrow with the fix. Sorry for the inconvenience.

**Comment by benjaminvolland** [comment]
Hi Robert, 
This issue is fix in the last version, the 2.5.8.
Thank you for the report
