### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference   

### ISSUE THREAD

**Issue by wliadmin** [teads/TeadsSDK-android#118]
I have got the below crash log on below version
```
compile ('tv.teads.sdk:androidsdk:2.5.12:fullRelease@aar') {
    transitive = true;
}
```
- Crash reproduced on Samsung Galaxy S4(Android 5.0 API 21)

- Also I have added below configuration on gradle file
minSdkVersion = 16
compileSdkVersion = 28
targetSdk = 23

- Used classpath 'com.android.tools.build:gradle:3.1.3'

**Crash:**
  ```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
        at tv.teads.sdk.adContent.views.AnimatedAdContentView.expand(AnimatedAdContentView.java:158)
        at ch.demo.ads.TeadsAdHandler.openInRead(TeadsAdHandler.java:206)
        at ch.demo.ads.TeadsAdHandler.access$1100(TeadsAdHandler.java:17)
        at ch.demo.ads.TeadsAdHandler$AdEventListener.teadsAdWillExpand(TeadsAdHandler.java:132)
        at tv.teads.sdk.publisher.BaseTeadsAd.adWillExpand(BaseTeadsAd.java:638)
        at tv.teads.sdk.adContent.AdContent.u(AdContent.java:248)
        at tv.teads.sdk.adContent.video.VideoAdContent.u(VideoAdContent.java:545)
        at tv.teads.sdk.adContainer.SimpleAdContainer.j(SimpleAdContainer.java:129)
        at tv.teads.sdk.publisher.BaseTeadsAd.adRequestShowContainer(BaseTeadsAd.java:667)
        at tv.teads.sdk.adContent.video.VideoAdContent.V(VideoAdContent.java:1066)
        at tv.teads.sdk.adContent.video.PlayerState.a(PlayerState.java:77)
        at tv.teads.sdk.adContent.video.VideoAdContent.W(VideoAdContent.java:1082)
        at tv.teads.sdk.adContent.video.VideoAdContent.c(VideoAdContent.java:695)
        at tv.teads.sdk.adContent.video.ui.player.nativePlayer.exoplayer.TeadsExoPlayer.onPlayerStateChanged(TeadsExoPlayer.java:506)
        at tv.teads.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:363)
        at tv.teads.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:98)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```
And i have used below code inside TeadsAdHandler>>openInRead() method.
 ```
private void openInRead() {
        if (mTeadsView == null) {
            mAdState.mAdViewHaveToBeOpen = true;
            return;
        }

        //Update the TeadsAdView to match the ViewGroup parent
        mTeadsView.updateSize(mListView);
        mTeadsView.setCollapsed();

        if (!mAdState.mAdViewHaveToBeOpen) {
            mAdState.mIsAnimating = true;
            mTeadsView.expand(new TeadsAnimationListener(true));
        } else {
            mAdState.mAdViewHaveToBeOpen = false;
            mTeadsView.setVisibility(View.VISIBLE);
            mAdState.mIsOpen = true;
            mTeadsAd.adViewDidExpand();
        }
    }
```

**Comment by HugoGresse** [comment]
Hi,

I would recommend not using the custom integration and use the standard inRead one. We are here to help if possible. We also have a new SDK version [here](http://mobile.teads.tv/sdk/documentation/v4/) which is much more simple to integrate.

**Comment by wliadmin** [comment]
Okay, But How we can prevent those type of crashes on the current version?
```
compile ('tv.teads.sdk:androidsdk:2.5.12:fullRelease@aar') {
    transitive = true;
}
```

**Comment by HugoGresse** [comment]
My recommendation will be to ping us on support-sdk@teads.tv
We try to do our best to support our SDKs. We still recommend to switch to the new SDKs and we can scheduled a call if needed.
