### ISSUE TITLE
Error in AdMob Mediation

### ISSUE THREAD

**Issue by takeharu** [teads/TeadsSDK-android#129]
If AdMob Mediation is selected from Additional Samples of the Teads SDK demo app and left for a while, the following error will occur after the video is reloaded several times, and the video can not be played with the same error on any screen .

I confirmed it on Android 8 and 9.
Android Studio Beta 1
Teads SDK version is 4.2.3

```
E/ExoPlayerImplInternal: Renderer error.
    tv.teads.android.exoplayer2.ExoPlaybackException
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:380)
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:367)
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796)
        at tv.teads.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365)
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
        at tv.teads.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
        at tv.teads.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:367) 
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796) 
        at tv.teads.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
        at tv.teads.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
        at tv.teads.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1786)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1767)
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:353)
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796) 
        at tv.teads.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:365) 
        at tv.teads.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494) 
        at tv.teads.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
        at tv.teads.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

I think that it need to execute `teadsAdBanner.clean()` in the `onDestroy()` method of the `tv.teads.adapter.admob.TeadsAdapter`.

**Comment by HugoGresse** [comment]
Hi,

Sorry for the delay. We'll look into it and get back to you. 

Best,

**Comment by HugoGresse** [comment]
Hi Takeharu, I've let the AdMob sample play for 10min without noticing any issue. 

The fact is that we cannot call `clean()` in the `onDestroy()` because we need the Teads instance alive to check a specific Teads metrics called the `adCall`. What you can do is make your own TeadsAdapter for AdMob with your specific logic. 
If your contract with Teads involve the `adCall` metric, plz submit your app prior to the release on support-sdk@teads.tv.

**Comment by takeharu** [comment]
@HugoGresse 

Thank you for confirmation.

I implemented TeadsAdapter by myself.
It works well now.

I would like to check the library when it is updated.

**Comment by HugoGresse** [comment]
Great, I'll update this ticket when it's done.

**Comment by HugoGresse** [comment]
SDK & adapter release 4.3.0 will include the fix, it is planned to be released within one month.

**Comment by HugoGresse** [comment]
Hi Takeharu,
The SDK v4.3.0 is now released. Let me know when you've tested it so we can close this.

**Comment by takeharu** [comment]
Thank you!
I confirmed that it works without any problems!

**Comment by HugoGresse** [comment]
Perfect, thanks.
