### ISSUE TITLE
Crash  when reusing the InReadAdView instance to load new ads

### ISSUE THREAD

**Issue by xardox69** [teads/TeadsSDK-android#130]
In InReadAdView listener PlayerConstants.COMPLETE event, I am trying to load a new ad using the same instance like:
when (state){
                            PlayerConstants.COMPLETE->{
                                teads_ad_view?.reset()
                            teads_ad_view?.load()
                            }
                        }
this gives Crash:
java.lang.NullPointerException: Attempt to invoke interface method 'void tv.teads.sdk.android.engine.ui.player.PlayerListener.j()' on a null object reference
        at tv.teads.sdk.android.engine.ui.player.nativePlayer.exoplayer.TeadsExoPlayer.onPlayerStateChanged(TeadsExoPlayer.java:479)
        at tv.teads.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:363)
        at tv.teads.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:98)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by benjaminvolland** [comment]
Hi @xardox69 , we will release a fix in the next release. In the meantime you can listen the `STOPPED` event instead of the `COMPLETE` for what you are trying to do. 
```PlayerConstants.STOPPED->{
teads_ad_view?.reset()
teads_ad_view?.load()
}
```

**Comment by HugoGresse** [comment]
Hi @xardox69

the latet SDK (4.2.4) fix this
