### ISSUE TITLE
NoClassDefFoundError after obfuscation

### ISSUE THREAD

**Issue by fighterpoul** [teads/TeadsSDK-android#85]
Hi, I'm using your library in version 2.4.1:fullRelease@aar
I'm also using ProGuard, my build tools are 25.0.1
I've pasted recommended proguard config from Wiki and it doesn't work. My app crashes at

`java.lang.NoClassDefFoundError: tv.teads.sdk.b.a.b
                                                     at tv.teads.sdk.b.a.a.a(Unknown Source)
                                                     at tv.teads.sdk.b.a.a.<init>(Unknown Source)
                                                     at tv.teads.sdk.adContent.e.a(Unknown Source)
                                                     at tv.teads.sdk.publisher.a$4.a(Unknown Source)
                                                     at tv.teads.adserver.a$6.run(Unknown Source)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5910)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)`

From my mapping.txt I know that problematic class is `tv.teads.sdk.util.chromeTabs.ServiceConnection -> tv.teads.sdk.b.a.b:`

**Comment by HugoGresse** [comment]
Hi @fighterpoul,

Thanks for reporting this, from where did you copy the proguard config? The proguard config are now managed by us through proguard consumer rules.

**Comment by fighterpoul** [comment]
It's strange because even if I put `-keep class tv.teads.** { *; }` in my config file I'm getting exception
`java.lang.NoClassDefFoundError: tv.teads.sdk.util.chromeTabs.ServiceConnection
                                                       at tv.teads.sdk.util.chromeTabs.ChromeCustomManager.a(Unknown Source)
                                                       at tv.teads.sdk.util.chromeTabs.ChromeCustomManager.<init>(Unknown Source)
                                                       at tv.teads.sdk.adContent.FullVideoAdContent.a(Unknown Source)
                                                       at tv.teads.sdk.publisher.BaseTeadsAd$4.onSuccess(Unknown Source)
                                                       at tv.teads.adserver.AdServerClient$6.run(Unknown Source)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5910)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)`

**Comment by HugoGresse** [comment]
that's weird, do you have this in production? On which device? I've retested in a blank app and I don't have any issue.

**Comment by fighterpoul** [comment]
I took a look around my configuration and issue wasn't produced by ProGuard. NoClassDefFoundError in log misleaded me, because it's typical exception when ProGuard had done to much. The real problem was excluding support from your library. I done that because AndroidStudio warned me that my app should use only one version of support library.
Sorry for misleading you.

**Comment by HugoGresse** [comment]
that's great! We will work to improve dependency management for the new major version, in the meantime you can exclude the support lib and add this: `
    compile 'com.android.support:customtabs:25.3.0'` I think.
